import type {
  EducationEntry,
  ExperienceEntry,
  PortfolioData,
  ProjectEntry,
  SkillGroupEntry,
} from "./types";

const published = "published" as const;

const experience: ExperienceEntry[] = [
  {
    id: "experience-ibusiness",
    type: "experience",
    company: {
      en: "iBusiness Corporation Co., Ltd.",
      th: "บริษัท ไอบิสซิเนส คอร์ปอเรชั่น จำกัด",
    },
    role: { en: "Web Developer / Programmer", th: "Web Developer / Programmer" },
    summary: {
      en: "Built and maintained business web applications.",
      th: "พัฒนาและดูแลเว็บแอปพลิเคชันสำหรับธุรกิจ",
    },
    startYear: 2016,
    endYear: 2019,
    current: false,
    status: published,
    sortOrder: 0,
  },
  {
    id: "experience-defense-me",
    type: "experience",
    company: { en: "Defense Me Co., Ltd.", th: "บริษัท ดีเฟนส์ มี จำกัด" },
    role: { en: "Web Developer / Programmer", th: "Web Developer / Programmer" },
    summary: {
      en: "Delivered responsive websites and back-office systems.",
      th: "พัฒนาเว็บไซต์ Responsive และระบบหลังบ้าน",
    },
    startYear: 2019,
    endYear: 2022,
    current: false,
    status: published,
    sortOrder: 1,
  },
  {
    id: "experience-freelancer",
    type: "experience",
    company: { en: "Freelancer", th: "นักพัฒนาอิสระ" },
    role: { en: "Web Developer / Programmer", th: "Web Developer / Programmer" },
    summary: {
      en: "Partnered with clients on full-stack websites and digital products.",
      th: "ร่วมงานกับลูกค้าเพื่อพัฒนาเว็บไซต์และผลิตภัณฑ์ดิจิทัลแบบ Full-Stack",
    },
    startYear: 2022,
    endYear: 2025,
    current: false,
    status: published,
    sortOrder: 2,
  },
  {
    id: "experience-healthy-smith",
    type: "experience",
    company: {
      en: "Healthy Smith Co., Ltd.",
      th: "บริษัท เฮลตี้ สมิธ จำกัด",
    },
    role: { en: "Web Developer / Programmer", th: "Web Developer / Programmer" },
    summary: {
      en: "Developing reliable, performance-focused web products.",
      th: "พัฒนาผลิตภัณฑ์เว็บที่เสถียรและให้ความสำคัญกับประสิทธิภาพ",
    },
    startYear: 2026,
    endYear: null,
    current: true,
    status: published,
    sortOrder: 3,
  },
];

const education: EducationEntry[] = [
  {
    id: "education-siam-tech",
    type: "education",
    institution: {
      en: "Siam Technological College",
      th: "วิทยาลัยเทคโนโลยีสยาม",
    },
    qualification: {
      en: "Vocational Certificate in Business Computer",
      th: "ประกาศนียบัตรวิชาชีพ สาขาคอมพิวเตอร์ธุรกิจ",
    },
    startYear: 2009,
    endYear: 2012,
    status: published,
    sortOrder: 0,
  },
  {
    id: "education-siam-university",
    type: "education",
    institution: { en: "Siam University", th: "มหาวิทยาลัยสยาม" },
    qualification: {
      en: "Bachelor of Science in Computer Science",
      th: "วิทยาศาสตรบัณฑิต สาขาวิทยาการคอมพิวเตอร์",
    },
    startYear: 2012,
    endYear: 2015,
    status: published,
    sortOrder: 1,
  },
];

const skillGroups: SkillGroupEntry[] = [
  {
    id: "skills-backend",
    type: "skillGroup",
    name: { en: "Backend", th: "แบ็กเอนด์" },
    skills: ["PHP", "Laravel", "MySQL", "RESTful API", "CMS"],
    status: published,
    sortOrder: 0,
  },
  {
    id: "skills-frontend",
    type: "skillGroup",
    name: { en: "Frontend", th: "ฟรอนต์เอนด์" },
    skills: ["JavaScript", "TypeScript", "HTML", "CSS3", "jQuery", "AngularJS", "AJAX"],
    status: published,
    sortOrder: 1,
  },
  {
    id: "skills-platform",
    type: "skillGroup",
    name: { en: "Platform & Delivery", th: "แพลตฟอร์มและการส่งมอบ" },
    skills: ["Git / GitHub", "Linux", "DevOps", "Web Hosting"],
    status: published,
    sortOrder: 2,
  },
  {
    id: "skills-quality",
    type: "skillGroup",
    name: { en: "Quality", th: "คุณภาพระบบ" },
    skills: ["Responsive Design", "Web Security", "Web Performance"],
    status: published,
    sortOrder: 3,
  },
  {
    id: "skills-growth",
    type: "skillGroup",
    name: { en: "Growth & Analytics", th: "การเติบโตและการวิเคราะห์" },
    skills: ["SEO", "GA4", "Search Console"],
    status: published,
    sortOrder: 4,
  },
];

const projects: ProjectEntry[] = [
  {
    id: "project-warehouse",
    type: "project",
    slug: "warehouse-management-system",
    title: { en: "Warehouse Management System", th: "ระบบบริหารคลังสินค้า" },
    summary: {
      en: "Operational workflows and dashboards for SKU imports, receiving, releasing, reporting, and tracking.",
      th: "ระบบงานและแดชบอร์ดสำหรับนำเข้า SKU รับสินค้า ปล่อยสินค้า รายงาน และติดตามสถานะ",
    },
    body: {
      en: "Maintained and improved a warehouse management system while building operational dashboards for day-to-day visibility.",
      th: "ดูแลและพัฒนาระบบบริหารคลังสินค้า พร้อมสร้างแดชบอร์ดเพื่อให้ทีมมองเห็นสถานะการดำเนินงานประจำวัน",
    },
    role: { en: "Full-Stack Web Developer", th: "นักพัฒนาเว็บ Full-Stack" },
    technologies: ["AngularJS", "TypeScript", "JavaScript", "Dashboard"],
    liveUrl: "",
    coverImage: "/images/portfolio/warehouse.webp",
    imageAlt: { en: "Warehouse interior", th: "ภายในคลังสินค้า" },
    featured: true,
    status: published,
    sortOrder: 0,
  },
  {
    id: "project-style-bangkok",
    type: "project",
    slug: "style-bangkok",
    title: { en: "Style Bangkok", th: "Style Bangkok" },
    summary: {
      en: "Responsive event and content website with a practical back office.",
      th: "เว็บไซต์อีเวนต์และคอนเทนต์แบบ Responsive พร้อมระบบหลังบ้าน",
    },
    body: {
      en: "Delivered front-end and content-management experiences across desktop, tablet, and mobile.",
      th: "พัฒนาหน้าเว็บไซต์และระบบจัดการเนื้อหาที่ใช้งานได้ทั้งเดสก์ท็อป แท็บเล็ต และมือถือ",
    },
    role: { en: "Full-Stack Web Developer", th: "นักพัฒนาเว็บ Full-Stack" },
    technologies: ["PHP", "HTML", "CSS3", "Responsive Design"],
    liveUrl: "",
    coverImage: "/images/portfolio/style-bangkok.webp",
    imageAlt: { en: "Style Bangkok website", th: "เว็บไซต์ Style Bangkok" },
    featured: true,
    status: published,
    sortOrder: 1,
  },
  {
    id: "project-asia-cement",
    type: "project",
    slug: "asia-cement",
    title: { en: "Asia Cement GPS Tracking", th: "ระบบ GPS Tracking สำหรับ Asia Cement" },
    summary: {
      en: "Back-office GPS tracking from vehicle departure through delivery and concrete pouring.",
      th: "ระบบหลังบ้านติดตาม GPS ตั้งแต่รถออกเดินทางจนถึงการส่งมอบและเทคอนกรีต",
    },
    body: {
      en: "Tracked delivery status, cement usage, loaded quantities, and operational data in one monitoring workflow.",
      th: "ติดตามสถานะการจัดส่ง การใช้ปูน ปริมาณบรรทุก และข้อมูลปฏิบัติการในระบบเดียว",
    },
    role: { en: "Full-Stack Web Developer", th: "นักพัฒนาเว็บ Full-Stack" },
    technologies: ["PHP", "Laravel", "MySQL", "Google Maps API", "GPS"],
    liveUrl: "",
    coverImage: "/images/portfolio/asia-cement.webp",
    imageAlt: { en: "Asia Cement tracking dashboard", th: "แดชบอร์ดติดตามงาน Asia Cement" },
    featured: true,
    status: published,
    sortOrder: 2,
  },
  {
    id: "project-lease-it",
    type: "project",
    slug: "lease-it",
    title: { en: "Lease It", th: "Lease It" },
    summary: {
      en: "Corporate financing website designed for clear content and responsive access.",
      th: "เว็บไซต์บริการสินเชื่อที่เน้นข้อมูลชัดเจนและรองรับทุกหน้าจอ",
    },
    body: { en: "", th: "" },
    role: { en: "Full-Stack Web Developer", th: "นักพัฒนาเว็บ Full-Stack" },
    technologies: ["PHP", "HTML", "CSS3", "Responsive Design"],
    liveUrl: "",
    coverImage: "/images/portfolio/lease-it.webp",
    imageAlt: { en: "Lease It website", th: "เว็บไซต์ Lease It" },
    featured: false,
    status: published,
    sortOrder: 3,
  },
  {
    id: "project-thai-health",
    type: "project",
    slug: "thai-health",
    title: { en: "Thai Health", th: "สสส." },
    summary: {
      en: "Content-rich public health website with responsive information architecture.",
      th: "เว็บไซต์ความรู้ด้านสุขภาพที่มีเนื้อหาหลากหลายและรองรับทุกอุปกรณ์",
    },
    body: { en: "", th: "" },
    role: { en: "Full-Stack Web Developer", th: "นักพัฒนาเว็บ Full-Stack" },
    technologies: ["PHP", "HTML", "CSS3", "CMS"],
    liveUrl: "",
    coverImage: "/images/portfolio/thai-health.webp",
    imageAlt: { en: "Thai Health website", th: "เว็บไซต์ สสส." },
    featured: false,
    status: published,
    sortOrder: 4,
  },
  {
    id: "project-cepa",
    type: "project",
    slug: "cepa",
    title: { en: "CEPA", th: "CEPA" },
    summary: {
      en: "Accessible research and public-information website.",
      th: "เว็บไซต์งานวิจัยและข้อมูลสาธารณะที่เข้าถึงได้ง่าย",
    },
    body: { en: "", th: "" },
    role: { en: "Full-Stack Web Developer", th: "นักพัฒนาเว็บ Full-Stack" },
    technologies: ["PHP", "HTML", "CSS3", "Responsive Design"],
    liveUrl: "",
    coverImage: "/images/portfolio/cepa.webp",
    imageAlt: { en: "CEPA website", th: "เว็บไซต์ CEPA" },
    featured: false,
    status: published,
    sortOrder: 5,
  },
  {
    id: "project-bangkok-electric-fair",
    type: "project",
    slug: "bangkok-electric-fair",
    title: { en: "Bangkok Electric Fair", th: "Bangkok Electric Fair" },
    summary: {
      en: "Event website combining visitor information, schedules, and content management.",
      th: "เว็บไซต์อีเวนต์ที่รวมข้อมูลผู้เข้าชม กำหนดการ และระบบจัดการเนื้อหา",
    },
    body: { en: "", th: "" },
    role: { en: "Full-Stack Web Developer", th: "นักพัฒนาเว็บ Full-Stack" },
    technologies: ["PHP", "HTML", "CSS3", "CMS"],
    liveUrl: "",
    coverImage: "/images/portfolio/bangkok-electric-fair.webp",
    imageAlt: { en: "Bangkok Electric Fair website", th: "เว็บไซต์ Bangkok Electric Fair" },
    featured: false,
    status: published,
    sortOrder: 6,
  },
  {
    id: "project-adventure-earth",
    type: "project",
    slug: "adventure-earth",
    title: { en: "Adventure Earth", th: "Adventure Earth" },
    summary: {
      en: "Travel website balancing destination imagery with clear booking-oriented content.",
      th: "เว็บไซต์ท่องเที่ยวที่ผสานภาพจุดหมายกับข้อมูลเพื่อการเดินทางอย่างชัดเจน",
    },
    body: { en: "", th: "" },
    role: { en: "Full-Stack Web Developer", th: "นักพัฒนาเว็บ Full-Stack" },
    technologies: ["PHP", "HTML", "CSS3", "Responsive Design"],
    liveUrl: "",
    coverImage: "/images/portfolio/adventure-earth.webp",
    imageAlt: { en: "Adventure Earth website", th: "เว็บไซต์ Adventure Earth" },
    featured: false,
    status: published,
    sortOrder: 7,
  },
  {
    id: "project-svoa",
    type: "project",
    slug: "svoa",
    title: { en: "SVOA", th: "SVOA" },
    summary: {
      en: "Corporate technology website with service and product content.",
      th: "เว็บไซต์องค์กรด้านเทคโนโลยีพร้อมข้อมูลบริการและผลิตภัณฑ์",
    },
    body: { en: "", th: "" },
    role: { en: "Full-Stack Web Developer", th: "นักพัฒนาเว็บ Full-Stack" },
    technologies: ["PHP", "HTML", "CSS3", "CMS"],
    liveUrl: "",
    coverImage: "/images/portfolio/svoa.webp",
    imageAlt: { en: "SVOA website", th: "เว็บไซต์ SVOA" },
    featured: false,
    status: published,
    sortOrder: 8,
  },
  {
    id: "project-baan-football",
    type: "project",
    slug: "baan-football",
    title: { en: "Baan.Football", th: "บ้านฟุตบอล" },
    summary: {
      en: "A real-time football platform built from the ground up with external data integration.",
      th: "แพลตฟอร์มฟุตบอลแบบเรียลไทม์ พัฒนาตั้งแต่เริ่มต้นพร้อมเชื่อมต่อข้อมูลภายนอก",
    },
    body: {
      en: "Built with Laravel, Livewire, and Reverb, including background jobs for ingesting and storing football data.",
      th: "พัฒนาด้วย Laravel, Livewire และ Reverb พร้อม Background Jobs สำหรับประมวลผลและจัดเก็บข้อมูลฟุตบอล",
    },
    role: { en: "Full-Stack Web Developer", th: "นักพัฒนาเว็บ Full-Stack" },
    technologies: ["Laravel", "Livewire", "Reverb", "REST API", "MySQL", "Linux"],
    liveUrl: "",
    coverImage: "/images/portfolio/baan-football.webp",
    imageAlt: { en: "Baan.Football live scores", th: "หน้าคะแนนสด Baan.Football" },
    featured: true,
    status: published,
    sortOrder: 9,
  },
];

export const defaultPortfolio: PortfolioData = {
  settings: {
    fullName: "Waranchai Pungwattananukul",
    seoTitle: {
      en: "Waranchai Pungwattananukul — Full-Stack Web Developer",
      th: "วรัญชัย พึ่งวัฒนานุกูล — นักพัฒนาเว็บไซต์ Full-Stack",
    },
    seoDescription: {
      en: "Full-Stack Web Developer in Bangkok building reliable digital products, platforms, and business systems.",
      th: "นักพัฒนาเว็บไซต์ Full-Stack ในกรุงเทพฯ ผู้สร้างผลิตภัณฑ์ดิจิทัล แพลตฟอร์ม และระบบธุรกิจที่เชื่อถือได้",
    },
    copy: {
      navAbout: { en: "About", th: "เกี่ยวกับ" },
      navWork: { en: "Work", th: "ผลงาน" },
      navExperience: { en: "Experience", th: "ประสบการณ์" },
      navSkills: { en: "Skills", th: "ทักษะ" },
      navContact: { en: "Contact", th: "ติดต่อ" },
      menu: { en: "Menu", th: "เมนู" },
      close: { en: "Close", th: "ปิด" },
      skip: { en: "Skip to content", th: "ข้ามไปยังเนื้อหา" },
      heroWorkAction: { en: "View selected work", th: "ดูผลงาน" },
      heroContactAction: { en: "Start a conversation", th: "คุยเรื่องโปรเจกต์" },
      aboutEyebrow: { en: "Profile / 01", th: "โปรไฟล์ / 01" },
      aboutTitle: {
        en: "Building useful things, thoughtfully.",
        th: "สร้างสิ่งที่มีประโยชน์อย่างตั้งใจ",
      },
      yearsLabel: { en: "Years of experience", th: "ปีของประสบการณ์" },
      projectsLabel: { en: "Selected projects", th: "ผลงานที่คัดสรร" },
      bilingualLabel: { en: "Bilingual communication", th: "สื่อสารสองภาษา" },
      workEyebrow: { en: "Selected work / 02", th: "ผลงานเด่น / 02" },
      workTitle: {
        en: "Systems, platforms, and websites made to work.",
        th: "ระบบ แพลตฟอร์ม และเว็บไซต์ที่สร้างมาเพื่อใช้งานจริง",
      },
      visitWebsite: { en: "Visit website", th: "เยี่ยมชมเว็บไซต์" },
      caseStudy: { en: "Case study", th: "กรณีศึกษา" },
      caseStudyDetails: { en: "Read case study", th: "อ่านกรณีศึกษา" },
      featured: { en: "Featured", th: "ผลงานเด่น" },
      archive: { en: "Archive", th: "ผลงานอื่น" },
      experienceEyebrow: { en: "Journey / 03", th: "เส้นทาง / 03" },
      experienceTitle: {
        en: "Experience that spans products and industries.",
        th: "ประสบการณ์จากหลากหลายผลิตภัณฑ์และอุตสาหกรรม",
      },
      education: { en: "Education", th: "การศึกษา" },
      present: { en: "Present", th: "ปัจจุบัน" },
      skillsEyebrow: { en: "Capabilities / 04", th: "ความสามารถ / 04" },
      skillsTitle: {
        en: "A practical, full-stack toolkit.",
        th: "เครื่องมือ Full-Stack สำหรับโจทย์ในโลกจริง",
      },
      contactEyebrow: { en: "Contact / 05", th: "ติดต่อ / 05" },
      backToTop: { en: "Back to top ↑", th: "กลับด้านบน ↑" },
    },
    eyebrow: { en: "Full-stack developer in Bangkok", th: "นักพัฒนา Full-Stack ในกรุงเทพฯ" },
    role: { en: "Full-Stack Web Developer", th: "นักพัฒนาเว็บไซต์ Full-Stack" },
    introduction: {
      en: "I build reliable, user-friendly web products that turn complex business needs into clear digital experiences.",
      th: "ผมพัฒนาเว็บที่เสถียร ใช้งานง่าย และเปลี่ยนความต้องการทางธุรกิจที่ซับซ้อนให้เป็นประสบการณ์ดิจิทัลที่ชัดเจน",
    },
    about: {
      en: "Experienced in PHP, Laravel, MySQL, JavaScript, REST APIs, responsive design, SEO, and web analytics. I enjoy solving complex problems, collaborating with teams, and using technology to help businesses achieve their digital goals.",
      th: "มีประสบการณ์ด้าน PHP, Laravel, MySQL, JavaScript, REST APIs, Responsive Design, SEO และ Web Analytics ชื่นชอบการแก้ปัญหาที่ซับซ้อน การทำงานร่วมกับทีม และการใช้เทคโนโลยีเพื่อช่วยให้ธุรกิจบรรลุเป้าหมายดิจิทัล",
    },
    availability: { en: "Available for selected projects", th: "พร้อมรับโปรเจกต์ที่เหมาะสม" },
    contactClosing: {
      en: "Have a product, platform, or business challenge in mind? Let's talk.",
      th: "มีไอเดียผลิตภัณฑ์ แพลตฟอร์ม หรือโจทย์ธุรกิจที่อยากพัฒนา มาคุยกันครับ",
    },
    email: "waranchai_new@hotmail.com",
    phone: "062-425-9965",
    location: { en: "Bangkok, Thailand", th: "กรุงเทพฯ ประเทศไทย" },
    portrait: "/images/portfolio/portrait.webp",
    portraitAlt: { en: "Portrait of Waranchai", th: "ภาพ Waranchai" },
  },
  experience,
  education,
  skillGroups,
  projects,
};
